joint_limits:
  shoulder_pan: {lower: -1.91986, upper: 1.91986}
  shoulder_lift: {lower: -1.74533, upper: 1.74533}
  elbow_flex: {lower: -1.69, upper: 1.69}
  wrist_flex: {lower: -1.65806, upper: 1.65806}
  wrist_roll: {lower: -2.74385, upper: 2.84121}
  gripper: {lower: 0.0, upper: 2.2028}
